# Generated by Django 2.2.4 on 2021-11-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
