# Generated by Django 2.2.4 on 2021-11-08 20:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'Billing Addresses & Buyers Details'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name_plural': 'Refunds - NOT READY YET'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses - DO NOT USE'},
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None),
        ),
    ]
