# Generated by Django 2.2.4 on 2021-11-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211109_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='apartment_address',
            new_name='towm_city',
        ),
    ]
