# Generated by Django 2.2.4 on 2021-11-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211109_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='towm_city',
            field=models.CharField(max_length=100, verbose_name='City/Town'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount Price DO NOT USE!'),
        ),
    ]
